// Category fallback images for the ranking cover system.
//
// Every image lives in public/covers/categories/ (generated by
// scripts/generate-cover-art.ts — fully self-hosted, zero copyright
// risk, zero external requests). Dedicated art exists for the 15
// slugs in KNOWN below; everything else aliases to the closest
// sibling, and "other" is the final neutral fallback. Never returns
// a broken URL.

const CARD_DIR = "/covers/categories";

// Sub-categories (and future categories) mapped to the nearest
// permanent artwork. Dedicated art slugs are NOT listed here.
const ALIASES: Record<string, string> = {
  // Taxonomy v2 (2026-09-30) primary categories without dedicated art
  // yet — aliased to the closest existing artwork. Never a broken URL.
  "fashion": "beauty-creators",
  "food": "other",
  "sports": "other",
  "entertainment": "other",
  "events-nightlife": "events",
  "art": "artists",
  // Legacy (pre-v2) slugs — kept so any lingering reference still
  // resolves instead of falling through to "other".
  // Music family
  "uk-rap-grime": "music",
  "underground-rap": "music",
  "kpop-dance": "music",
  // Club culture family
  "dj-genres": "djs-club-culture",
  "club-nights": "djs-club-culture",
  "nightlife-personalities": "djs-club-culture",
  // Creator family
  "radio-livestream": "digital-creators",
  "food-drink-creators": "digital-creators",
  "streetwear-fashion-creators": "beauty-creators",
  "alternative-fashion": "beauty-creators",
  "independent-art-zines": "artists",
  // Culture family
  "anime-japanese-subculture": "anime",
  "gaming-esports": "gaming",
};

const KNOWN = new Set([
  "anime",
  "gaming",
  "manga",
  "cosplay",
  "digital-creators",
  "music",
  "artists",
  "university",
  "events",
  "other",
  "tabletop-tcg-roleplaying",
  "university-societies",
  "underground-music",
  "djs-club-culture",
  "beauty-creators",
]);

export function resolveCategoryArtSlug(categorySlug: string | null | undefined): string {
  if (!categorySlug) return "other";
  if (KNOWN.has(categorySlug)) return categorySlug;
  const alias = ALIASES[categorySlug];
  if (alias && KNOWN.has(alias)) return alias;
  // Prefix fallbacks for future slugs in the same family.
  if (categorySlug.startsWith("anime")) return "anime";
  if (categorySlug.startsWith("gaming")) return "gaming";
  if (categorySlug.startsWith("music")) return "music";
  if (categorySlug.startsWith("manga")) return "manga";
  return "other";
}

// 600x400 — ranking cards.
export function getCategoryFallbackCard(categorySlug: string | null | undefined): string {
  return `${CARD_DIR}/${resolveCategoryArtSlug(categorySlug)}-card.webp`;
}

// 1600x450 — category banners.
export function getCategoryFallbackBanner(categorySlug: string | null | undefined): string {
  return `${CARD_DIR}/${resolveCategoryArtSlug(categorySlug)}-banner.webp`;
}

// Final neutral fallback when everything else fails.
export function getNeutralFallbackCard(): string {
  return `${CARD_DIR}/other-card.webp`;
}
