// -----------------------------------------------------------------------
// Anime nominee sets (2026-09-30): 10 factual nominees for each of the 29
// non-flagship Anime rankings (entity-safe: series, characters, ships,
// songs — no real people). Idempotent via findNomineeByRankingAndName.
// Runs after the required-ranking seeds in ensureMigrated().
// -----------------------------------------------------------------------
import { findUserByEmail } from "./users";
import { createProfile, findNomineeByRankingAndName } from "./profiles";
import { findRequiredRankingId } from "./seedFlagshipNominees";

const TEAM_EMAIL = "team@rephear.com";

const ANIME_NOMINEES: Record<string, { name: string; bio: string }[]> = {
  "best-anime-right-now": [
      { name: "Solo Leveling Season 2", bio: "2025's record-breaking A-1 Pictures hit" },
      { name: "Frieren: Beyond Journey's End Season 2", bio: "Madhouse's beloved fantasy returns January 2026" },
      { name: "Jujutsu Kaisen Season 3", bio: "MAPPA's Culling Game arc, January 2026" },
      { name: "Demon Slayer: Infinity Castle", bio: "ufotable's 2025 film trilogy opener" },
      { name: "One Piece", bio: "Still sailing since 1999" },
      { name: "Kaiju No. 8 Season 2", bio: "2025's monster-battling return" },
      { name: "Dandadan Season 2", bio: "Science SARU's occult rom-com continues" },
      { name: "Re:Zero Season 3", bio: "White Fox's isekai epic rolls on" },
      { name: "The Apothecary Diaries Season 2", bio: "2025's mystery hit" },
      { name: "Oshi no Ko Season 3", bio: "Doga Kobo's idol drama returns January 2026" },
    ],
  "best-anime-of-2026": [
      { name: "Frieren: Beyond Journey's End Season 2", bio: "Winter 2026's most anticipated return" },
      { name: "Jujutsu Kaisen Season 3", bio: "The Culling Game finally animated" },
      { name: "Oshi no Ko Season 3", bio: "The idol industry's dark side continues" },
      { name: "Hell's Paradise Season 2", bio: "Gabimaru's return after five years" },
      { name: "Golden Kamuy Final Season", bio: "The beloved adventure concludes" },
      { name: "My Hero Academia: Vigilantes Season 2", bio: "The street-level hero spinoff continues" },
      { name: "Fire Force Season 3 Part 2", bio: "David Production's fiery finale" },
      { name: "Trigun Stargaze", bio: "Vash the Stampede's next chapter" },
      { name: "Fate/strange Fake", bio: "A-1 Pictures' long-awaited Grail War" },
      { name: "MF Ghost Season 3", bio: "Initial D successor's racing drama" },
    ],
  "most-overrated-anime-right-now": [
      { name: "Sword Art Online", bio: "The isekai that launched a thousand debates" },
      { name: "Demon Slayer", bio: "ufotable spectacle or style over substance?" },
      { name: "Tokyo Revengers", bio: "Delinquent time-travel drama" },
      { name: "Oshi no Ko", bio: "Idol-industry hit with divisive ending" },
      { name: "Jujutsu Kaisen", bio: "MAPPA's shonen juggernaut" },
      { name: "My Hero Academia", bio: "The superhero shonen of a generation" },
      { name: "Chainsaw Man", bio: "MAPPA's gory subversion" },
      { name: "Solo Leveling", bio: "Power-fantasy phenomenon" },
      { name: "Re:Zero", bio: "Brutal isekai with a devoted fandom" },
      { name: "Attack on Titan", bio: "The phenomenon everyone argues about" },
    ],
  "most-underrated-anime": [
      { name: "Odd Taxi", bio: "2021 mystery masterpiece hiding in plain sight" },
      { name: "Ping Pong the Animation", bio: "Masaaki Yuasa's sports character study" },
      { name: "Mushishi", bio: "Quiet episodic folklore at its finest" },
      { name: "Kaiba", bio: "Yuasa's surreal memory-swapping sci-fi" },
      { name: "Land of the Lustrous", bio: "Orange's gorgeous CGI gem" },
      { name: "Made in Abyss", bio: "Beautiful and brutal descent" },
      { name: "Vinland Saga", bio: "Makoto Yukimura's Viking epic" },
      { name: "86 Eighty Six", bio: "Mecha drama with real teeth" },
      { name: "Paranoia Agent", bio: "Satoshi Kon's unsettling social thriller" },
      { name: "Showa Genroku Rakugo Shinju", bio: "A rakugo drama like nothing else" },
    ],
  "anime-everyone-should-watch-once": [
      { name: "Cowboy Bebop", bio: "1998 space-noir landmark" },
      { name: "Fullmetal Alchemist: Brotherhood", bio: "The complete 64-episode classic" },
      { name: "Steins;Gate", bio: "Time-travel thriller done right" },
      { name: "Monster", bio: "Naoki Urasawa's 74-episode psychological epic" },
      { name: "Vinland Saga", bio: "A Viking tale of violence and redemption" },
      { name: "March Comes in Like a Lion", bio: "Shogi, depression, and found family" },
      { name: "Ping Pong the Animation", bio: "Eleven episodes of pure character" },
      { name: "Mushishi", bio: "Gentle supernatural anthology" },
      { name: "Showa Genroku Rakugo Shinju", bio: "Period drama of art and regret" },
      { name: "Haibane Renmei", bio: "Yoshitoshi ABe's quiet allegory" },
    ],
  "best-anime-for-beginners": [
      { name: "Death Note", bio: "The gateway thriller" },
      { name: "One Punch Man", bio: "Superhero satire in 12 episodes" },
      { name: "My Hero Academia", bio: "Classic shonen, easy on-ramp" },
      { name: "Demon Slayer", bio: "Gorgeous and straightforward" },
      { name: "Spy x Family", bio: "Wholesome spy comedy" },
      { name: "Your Name", bio: "Makoto Shinkai's global hit film" },
      { name: "Attack on Titan", bio: "The hook is instant" },
      { name: "Fullmetal Alchemist: Brotherhood", bio: "Complete story, zero filler" },
      { name: "Cowboy Bebop", bio: "26 episodes, endlessly rewatchable" },
      { name: "Spirited Away", bio: "Miyazaki's Oscar-winning classic" },
    ],
  "anime-rewatch-first-time": [
      { name: "Your Name", bio: "Shinkai's body-swap romance" },
      { name: "Steins;Gate", bio: "Every rewatch reveals new clues" },
      { name: "Clannad: After Story", bio: "The emotional gold standard" },
      { name: "Puella Magi Madoka Magica", bio: "Twelve episodes that redefine the genre" },
      { name: "Re:Zero", bio: "Suffering worth reliving" },
      { name: "Attack on Titan", bio: "Foreshadowing you missed the first time" },
      { name: "Made in Abyss", bio: "Wonder and dread in equal measure" },
      { name: "Violet Evergarden", bio: "Kyoto Animation's emotional peak" },
      { name: "Anohana", bio: "The flower we saw that day" },
      { name: "A Silent Voice", bio: "Kyoto Animation's redemption story" },
    ],
  "best-anime-protagonist": [
      { name: "Eren Yeager", bio: "Protagonist of Attack on Titan" },
      { name: "Naruto Uzumaki", bio: "Protagonist of Naruto" },
      { name: "Monkey D. Luffy", bio: "Protagonist of One Piece" },
      { name: "Goku", bio: "Protagonist of Dragon Ball" },
      { name: "Edward Elric", bio: "Protagonist of Fullmetal Alchemist" },
      { name: "Spike Spiegel", bio: "Protagonist of Cowboy Bebop" },
      { name: "Shinji Ikari", bio: "Protagonist of Neon Genesis Evangelion" },
      { name: "Light Yagami", bio: "Protagonist of Death Note" },
      { name: "Denji", bio: "Protagonist of Chainsaw Man" },
      { name: "Thorfinn", bio: "Protagonist of Vinland Saga" },
    ],
  "best-anime-villain": [
      { name: "Madara Uchiha", bio: "Antagonist of Naruto Shippuden" },
      { name: "Sosuke Aizen", bio: "Antagonist of Bleach" },
      { name: "Meruem", bio: "Chimera Ant King in Hunter x Hunter" },
      { name: "Griffith", bio: "Antagonist of Berserk" },
      { name: "Johan Liebert", bio: "Antagonist of Monster" },
      { name: "Frieza", bio: "Antagonist of Dragon Ball Z" },
      { name: "Pain", bio: "Antagonist of Naruto Shippuden" },
      { name: "Muzan Kibutsuji", bio: "Antagonist of Demon Slayer" },
      { name: "Ryomen Sukuna", bio: "Antagonist of Jujutsu Kaisen" },
      { name: "Tomura Shigaraki", bio: "Antagonist of My Hero Academia" },
    ],
  "anime-characters-most-aura": [
      { name: "Satoru Gojo", bio: "The strongest sorcerer in Jujutsu Kaisen" },
      { name: "Levi Ackerman", bio: "Humanity's strongest soldier in Attack on Titan" },
      { name: "Ryomen Sukuna", bio: "The King of Curses" },
      { name: "Madara Uchiha", bio: "The Ghost of the Uchiha" },
      { name: "Itachi Uchiha", bio: "Naruto's tragic prodigy" },
      { name: "Kakashi Hatake", bio: "The Copy Ninja" },
      { name: "Roronoa Zoro", bio: "One Piece's swordsman" },
      { name: "Killua Zoldyck", bio: "Hunter x Hunter's assassin prodigy" },
      { name: "Sung Jinwoo", bio: "The Shadow Monarch of Solo Leveling" },
      { name: "Yoruichi Shihoin", bio: "Bleach's Flash Goddess" },
    ],
  "most-iconic-anime-character": [
      { name: "Goku", bio: "Dragon Ball's Super Saiyan" },
      { name: "Naruto Uzumaki", bio: "The Seventh Hokage" },
      { name: "Monkey D. Luffy", bio: "The future Pirate King" },
      { name: "Pikachu", bio: "Pokémon's global mascot" },
      { name: "Sailor Moon", bio: "Usagi Tsukino, the Pretty Guardian" },
      { name: "Astro Boy", bio: "Osamu Tezuka's 1963 pioneer" },
      { name: "Doraemon", bio: "The robotic cat from the future" },
      { name: "Totoro", bio: "Studio Ghibli's forest spirit" },
      { name: "Shinji Ikari", bio: "Evangelion's reluctant pilot" },
      { name: "Light Yagami", bio: "Death Note's Kira" },
    ],
  "best-female-anime-character": [
      { name: "Mikasa Ackerman", bio: "Attack on Titan's devoted soldier" },
      { name: "Asuna Yuuki", bio: "Sword Art Online's Lightning Flash" },
      { name: "Rem", bio: "Re:Zero's loyal maid" },
      { name: "Zero Two", bio: "Darling in the Franxx's partner killer" },
      { name: "Violet Evergarden", bio: "The Auto Memory Doll" },
      { name: "Motoko Kusanagi", bio: "Ghost in the Shell's Major" },
      { name: "Saber", bio: "Fate's King of Knights" },
      { name: "Nami", bio: "One Piece's navigator" },
      { name: "Nezuko Kamado", bio: "Demon Slayer's demon sister" },
      { name: "Frieren", bio: "The elven mage beyond journey's end" },
    ],
  "best-anime-duo": [
      { name: "Naruto & Sasuke", bio: "Naruto's rival brothers-in-arms" },
      { name: "Goku & Vegeta", bio: "Dragon Ball's eternal rivals" },
      { name: "Gon & Killua", bio: "Hunter x Hunter's best friends" },
      { name: "Spike & Jet", bio: "Cowboy Bebop's bounty hunters" },
      { name: "Edward & Alphonse Elric", bio: "Fullmetal Alchemist's brothers" },
      { name: "Luffy & Zoro", bio: "One Piece's captain and swordsman" },
      { name: "Tanjiro & Nezuko", bio: "Demon Slayer's siblings" },
      { name: "Ash & Pikachu", bio: "Pokémon's iconic partners" },
      { name: "Light & L", bio: "Death Note's cat-and-mouse geniuses" },
      { name: "Mob & Reigen", bio: "Mob Psycho 100's esper and con artist" },
    ],
  "best-anime-rivalry": [
      { name: "Naruto vs Sasuke", bio: "Naruto's defining rivalry" },
      { name: "Goku vs Vegeta", bio: "Dragon Ball's Saiyan rivalry" },
      { name: "Ash vs Gary", bio: "Pokémon's original rivalry" },
      { name: "Deku vs Bakugo", bio: "My Hero Academia's childhood rivals" },
      { name: "Light vs L", bio: "Death Note's battle of wits" },
      { name: "Lelouch vs Suzaku", bio: "Code Geass's ideological clash" },
      { name: "Gon vs Hisoka", bio: "Hunter x Hunter's deadly obsession" },
      { name: "Yugi vs Kaiba", bio: "Yu-Gi-Oh!'s card-game rivalry" },
      { name: "Takumi vs Ryosuke", bio: "Initial D's mountain-pass duel" },
      { name: "Spike vs Vicious", bio: "Cowboy Bebop's fatal history" },
    ],
  "best-anime-couple": [
      { name: "Naruto & Hinata", bio: "Naruto's canon couple" },
      { name: "Goku & Chi-Chi", bio: "Dragon Ball's married couple" },
      { name: "Edward & Winry", bio: "Fullmetal Alchemist's endgame" },
      { name: "Kirito & Asuna", bio: "Sword Art Online's couple" },
      { name: "Inuyasha & Kagome", bio: "Inuyasha's time-crossed pair" },
      { name: "Takeo & Rinko", bio: "My Love Story!!'s wholesome couple" },
      { name: "Holo & Lawrence", bio: "Spice and Wolf's traveling pair" },
      { name: "Shirou & Saber", bio: "Fate/stay night's Fate route" },
      { name: "Simon & Nia", bio: "Gurren Lagann's tragic romance" },
      { name: "Ash & Serena", bio: "Pokémon XY's beloved pairing" },
    ],
  "best-anime-friendship": [
      { name: "Gon & Killua", bio: "Hunter x Hunter's unbreakable bond" },
      { name: "Yuji & Todo", bio: "Jujutsu Kaisen's besto frendo" },
      { name: "Naruto & Shikamaru", bio: "Naruto's lifelong friends" },
      { name: "Gintoki & Shinpachi", bio: "Gintama's odd-jobs duo" },
      { name: "Edward & Alphonse", bio: "Brothers before alchemists" },
      { name: "Spike & Jet", bio: "Bebop's found family" },
      { name: "Simon & Kamina", bio: "Gurren Lagann's brotherhood" },
      { name: "Mob & Reigen", bio: "Mob Psycho 100's unlikely pair" },
      { name: "Tanjiro & Zenitsu", bio: "Demon Slayer's comrades" },
      { name: "Deku & All Might", bio: "My Hero Academia's mentor bond" },
    ],
  "best-anime-character-development": [
      { name: "Eren Yeager", bio: "Attack on Titan's transformation" },
      { name: "Thorfinn", bio: "Vinland Saga's path to peace" },
      { name: "Vegeta", bio: "Dragon Ball's pride redeemed" },
      { name: "Gaara", bio: "Naruto's monster to Kazekage" },
      { name: "Meruem", bio: "Hunter x Hunter's king humanized" },
      { name: "Ken Kaneki", bio: "Tokyo Ghoul's descent and return" },
      { name: "Guts", bio: "Berserk's lifelong struggle" },
      { name: "Shinji Ikari", bio: "Evangelion's painful growth" },
      { name: "Askeladd", bio: "Vinland Saga's layered schemer" },
      { name: "Arataka Reigen", bio: "Mob Psycho 100's fraud with a heart" },
    ],
  "best-anime-fight-of-all-time": [
      { name: "Naruto vs Sasuke — Final Valley", bio: "Naruto Shippuden's climactic duel" },
      { name: "Goku vs Jiren — Tournament of Power", bio: "Dragon Ball Super's Ultra Instinct debut" },
      { name: "Levi vs Kenny — Attack on Titan", bio: "Season 3's alleyway showdown" },
      { name: "Gon vs Pitou — Chimera Ant arc", bio: "Hunter x Hunter's darkest transformation" },
      { name: "Luffy vs Kaido — Wano", bio: "One Piece's Gear 5 awakening" },
      { name: "Tanjiro vs Rui — Natagumo Mountain", bio: "Demon Slayer's Hinokami Kagura debut" },
      { name: "Mob vs Mogami — Mob Psycho 100", bio: "Season 2's psychic possession battle" },
      { name: "Spike vs Vicious — Ballad of Fallen Angels", bio: "Cowboy Bebop's church showdown" },
      { name: "Netero vs Meruem — Chimera Ant arc", bio: "Hunter x Hunter's battle of ideals" },
      { name: "All Might vs All For One — Kamino", bio: "My Hero Academia's passing of the torch" },
    ],
  "best-anime-power-system": [
      { name: "Nen — Hunter x Hunter", bio: "The gold standard of hard magic" },
      { name: "Chakra — Naruto", bio: "Hand signs and nature transformation" },
      { name: "Stands — JoJo's Bizarre Adventure", bio: "Manifestations of fighting spirit" },
      { name: "Devil Fruits — One Piece", bio: "Power at the cost of the sea" },
      { name: "Quirks — My Hero Academia", bio: "Superpowers as society's fabric" },
      { name: "Cursed Energy — Jujutsu Kaisen", bio: "Born from negative emotion" },
      { name: "Alchemy — Fullmetal Alchemist", bio: "Equivalent exchange" },
      { name: "Ki — Dragon Ball", bio: "The original battle aura" },
      { name: "Grimoire Magic — Black Clover", bio: "Spellbooks and mana zones" },
      { name: "Hamon — JoJo's Bizarre Adventure", bio: "The Ripple of Phantom Blood" },
    ],
  "best-anime-worldbuilding": [
      { name: "One Piece", bio: "Decades of islands, lore, and history" },
      { name: "Attack on Titan", bio: "Every answer recontextualizes everything" },
      { name: "Made in Abyss", bio: "The Abyss's layered horrors" },
      { name: "Mushishi", bio: "A living folkloric Japan" },
      { name: "Fullmetal Alchemist: Brotherhood", bio: "Amestris's alchemy and war" },
      { name: "Hunter x Hunter", bio: "From Hunter exams to the Dark Continent" },
      { name: "Legend of the Galactic Heroes", bio: "A galaxy of politics and war" },
      { name: "Berserk", bio: "Kentaro Miura's dark medieval world" },
      { name: "Nausicaä of the Valley of the Wind", bio: "Miyazaki's toxic jungle ecology" },
      { name: "Land of the Lustrous", bio: "A crystalline far-future Earth" },
    ],
  "best-anime-plot-twist": [
      { name: "Itachi's true motives — Naruto Shippuden", bio: "The massacre's real story" },
      { name: "Reiner and Bertholdt are Titans — Attack on Titan", bio: "Season 2's wall-shattering reveal" },
      { name: "The basement reveal — Attack on Titan", bio: "The world's true history" },
      { name: "Near and Mello succeed L — Death Note", bio: "L's successors close the net" },
      { name: "The truth of the contract — Madoka Magica", bio: "Kyubey's entropy gambit" },
      { name: "Griffith's betrayal — Berserk", bio: "The Eclipse" },
      { name: "Aizen's betrayal — Bleach", bio: "The captain behind everything" },
      { name: "Shou Tucker's chimera — Fullmetal Alchemist", bio: "The Sewing-Life Alchemist's crime" },
      { name: "Zero Requiem — Code Geass", bio: "Lelouch's final plan" },
      { name: "Eren's true plan — Attack on Titan", bio: "The Rumbling's real purpose" },
    ],
  "best-anime-opening": [
      { name: "Gurenge — LiSA (Demon Slayer)", bio: "The OP that defined 2019" },
      { name: "Unravel — TK (Tokyo Ghoul)", bio: "TK from Ling Tosite Sigure's scream" },
      { name: "Tank! — The Seatbelts (Cowboy Bebop)", bio: "Three minutes of pure jazz" },
      { name: "A Cruel Angel's Thesis — Yoko Takahashi (Evangelion)", bio: "The most covered anime song ever" },
      { name: "Kaibutsu — YOASOBI (Beastars)", bio: "YOASOBI's beastly hit" },
      { name: "Inferno — Mrs. Green Apple (Fire Force)", bio: "Season 1's fiery opener" },
      { name: "Otonoke — Creepy Nuts (Dandadan)", bio: "The viral 2024 opener" },
      { name: "Idol — YOASOBI (Oshi no Ko)", bio: "Broke streaming records worldwide" },
      { name: "Silhouette — KANA-BOON (Naruto Shippuden)", bio: "The fan-favorite late-series OP" },
      { name: "Again — YUI (Fullmetal Alchemist: Brotherhood)", bio: "Brotherhood's first opening" },
    ],
  "best-anime-ending-song": [
      { name: "Fly Me to the Moon — Claire (Neon Genesis Evangelion)", bio: "The iconic ED" },
      { name: "Wind — Akeboshi (Naruto)", bio: "Naruto's first ending" },
      { name: "Uso — SID (Fullmetal Alchemist: Brotherhood)", bio: "Brotherhood's first ending" },
      { name: "Styx Helix — MYTH & ROID (Re:Zero)", bio: "Re:Zero's haunting first ED" },
      { name: "Stay Alive — Emilia (Re:Zero)", bio: "Re:Zero's second ending" },
      { name: "Fuwa Fuwa Time — Ho-kago Tea Time (K-On!)", bio: "The beloved HTT ending" },
      { name: "Akuma no Ko — Ai Higuchi (Attack on Titan)", bio: "The Final Season's mournful ED" },
      { name: "Kimi no Shiranai Monogatari — supercell (Bakemonogatari)", bio: "The ED that launched supercell" },
      { name: "Magia — Kalafina (Madoka Magica)", bio: "Madoka Magica's dark ending theme" },
      { name: "Dango Daikazoku — Chata (Clannad)", bio: "The dango family lullaby" },
    ],
  "best-anime-soundtrack": [
      { name: "Cowboy Bebop — Yoko Kanno", bio: "The Seatbelts' genre-hopping jazz" },
      { name: "Attack on Titan — Hiroyuki Sawano", bio: "Sawano's bombastic vocal tracks" },
      { name: "Naruto — Toshio Masuda", bio: "Flutes, drums, and nostalgia" },
      { name: "Demon Slayer — Yuki Kajiura & Go Shiina", bio: "Orchestral intensity" },
      { name: "Your Lie in April — Masaru Yokoyama", bio: "Classical heartbreak" },
      { name: "Made in Abyss — Kevin Penkin", bio: "Otherworldly and haunting" },
      { name: "Samurai Champloo — Nujabes", bio: "Lo-fi hip-hop meets Edo Japan" },
      { name: "Neon Genesis Evangelion — Shiro Sagisu", bio: "Sagisu's orchestral dread" },
      { name: "Frieren — Evan Call", bio: "Gentle, timeless fantasy scoring" },
      { name: "Studio Ghibli films — Joe Hisaishi", bio: "Miyazaki's musical soulmate" },
    ],
  "best-anime-animation": [
      { name: "Demon Slayer — ufotable", bio: "Digital-era sakuga benchmark" },
      { name: "Mob Psycho 100 — Bones", bio: "Yuasa-style psychic mayhem" },
      { name: "Fate/stay night: Heaven's Feel — ufotable", bio: "Film-trilogy visual peak" },
      { name: "Violet Evergarden — Kyoto Animation", bio: "KyoAni's most lavish TV work" },
      { name: "Jujutsu Kaisen — MAPPA", bio: "Season 2's hand-drawn spectacle" },
      { name: "Redline — Madhouse", bio: "Seven years of hand-drawn racing" },
      { name: "Akira — TMS Entertainment", bio: "1988's still-unmatched detail" },
      { name: "Your Name — CoMix Wave Films", bio: "Shinkai's light-drenched feature" },
      { name: "Sword of the Stranger — Bones", bio: "A samurai duel for the ages" },
      { name: "Promare — Trigger", bio: "Trigger's neon inferno" },
    ],
  "most-beautiful-anime": [
      { name: "Your Name", bio: "Makoto Shinkai's 2016 phenomenon" },
      { name: "Violet Evergarden", bio: "Kyoto Animation's visual poetry" },
      { name: "Made in Abyss", bio: "Beauty that hides horror" },
      { name: "Mushishi", bio: "Watercolor stillness" },
      { name: "A Silent Voice", bio: "KyoAni's tender feature" },
      { name: "The Garden of Words", bio: "Shinkai's rain-soaked short" },
      { name: "Land of the Lustrous", bio: "Orange's crystalline CGI" },
      { name: "Frieren: Beyond Journey's End", bio: "Quiet, painterly fantasy" },
      { name: "Nausicaä of the Valley of the Wind", bio: "Miyazaki's 1984 epic" },
      { name: "Wolf Children", bio: "Mamoru Hosoda's pastoral tale" },
    ],
  "most-emotional-anime": [
      { name: "Your Lie in April", bio: "Music, grief, and first love" },
      { name: "Clannad: After Story", bio: "The tearjerker gold standard" },
      { name: "Anohana", bio: "The flower we saw that day" },
      { name: "A Silent Voice", bio: "Bullying, guilt, and redemption" },
      { name: "Grave of the Fireflies", bio: "Ghibli's devastating war film" },
      { name: "Violet Evergarden", bio: "Learning what love means" },
      { name: "Frieren: Beyond Journey's End", bio: "Grief measured in centuries" },
      { name: "Made in Abyss", bio: "Wonder wrapped around loss" },
      { name: "March Comes in Like a Lion", bio: "Depression and found family" },
      { name: "Banana Fish", bio: "A 2018 tragedy that still hurts" },
    ],
  "funniest-anime": [
      { name: "Gintama", bio: "The comedy king of Jump" },
      { name: "Konosuba", bio: "The dysfunctional isekai party" },
      { name: "Nichijou", bio: "Kyoto Animation's surreal school comedy" },
      { name: "The Disastrous Life of Saiki K", bio: "Psychic deadpan chaos" },
      { name: "Daily Lives of High School Boys", bio: "Sunrise's skit classic" },
      { name: "Grand Blue", bio: "Diving club debauchery" },
      { name: "Cromartie High School", bio: "Delinquent absurdism" },
      { name: "Prison School", bio: "Over-the-top ecchi comedy" },
      { name: "Osomatsu-san", bio: "Six NEET brothers, endless gags" },
      { name: "Spy x Family", bio: "Anya's faces carry the show" },
    ],
  "anime-strongest-fandom": [
      { name: "One Piece", bio: "The global pirate armada" },
      { name: "Naruto", bio: "Believe it since 2002" },
      { name: "Dragon Ball", bio: "The fandom that raised generations" },
      { name: "Attack on Titan", bio: "Theories for a decade straight" },
      { name: "Jujutsu Kaisen", bio: "The new-gen powerhouse" },
      { name: "Demon Slayer", bio: "Box-office-breaking devotees" },
      { name: "My Hero Academia", bio: "Plus Ultra worldwide" },
      { name: "JoJo's Bizarre Adventure", bio: "Memes as a lifestyle" },
      { name: "Gundam", bio: "Gunpla builders since 1979" },
      { name: "Neon Genesis Evangelion", bio: "Still debating the ending" },
    ],
};

export async function attachAnimeNominees(): Promise<void> {
  try {
    const team = await findUserByEmail(TEAM_EMAIL);
    if (!team) return;
    for (const [slug, nominees] of Object.entries(ANIME_NOMINEES)) {
      // Slug first, exact-title fallback (reused rows keep original slugs).
      const rankingId = await findRequiredRankingId(slug);
      if (!rankingId) continue;
      for (const n of nominees) {
        const dupe = await findNomineeByRankingAndName(rankingId, n.name);
        if (dupe) continue;
        await createProfile({
          rankingId,
          name: n.name,
          bio: n.bio ?? "",
          addedBy: team.id,
        });
      }
    }
  } catch {
    // Best-effort seed step: never break startup.
  }
}
