// -----------------------------------------------------------------------
// Manga nominee sets (2026-09-30): 10 factual nominees for each of the 29
// non-flagship required Manga rankings (entity-safe fictional entities
// only — series, characters, pairs; no real people's names).
// Kept separate from requiredRankings.ts so the registry stays a pure
// title/taxonomy source of truth. Idempotent: nominees are matched by
// (ranking_id, name) via findNomineeByRankingAndName; existing rows are
// never duplicated. Runs after the required-ranking seeds in
// ensureMigrated(). Best-effort: never throws.
// -----------------------------------------------------------------------
import { findUserByEmail } from "./users";
import { createProfile, findNomineeByRankingAndName } from "./profiles";
import { findRequiredRankingId } from "./seedFlagshipNominees";

const TEAM_EMAIL = "team@rephear.com";

const MANGA_NOMINEES: Record<string, { name: string; bio: string }[]> = {
  "best-manga-right-now": [
    { name: "One Piece", bio: "Eiichiro Oda's pirate epic, still setting sales records" },
    { name: "Jujutsu Kaisen", bio: "Gege Akutami's sorcery blockbuster" },
    { name: "My Hero Academia", bio: "Kohei Horikoshi's superhero phenomenon" },
    { name: "Chainsaw Man", bio: "Tatsuki Fujimoto's chaotic devil-hunting hit" },
    { name: "Spy x Family", bio: "Tatsuya Endo's beloved spy-family comedy" },
    { name: "Frieren: Beyond Journey's End", bio: "Kanehito Yamada's fantasy about time and grief" },
    { name: "Oshi no Ko", bio: "Aka Akasaka's idol-industry drama" },
    { name: "Kaiju No. 8", bio: "Naoya Matsumoto's monster-slaying sensation" },
    { name: "Dandadan", bio: "Yukinobu Tatsu's occult action-comedy" },
    { name: "Sakamoto Days", bio: "Yuto Suzuki's hitman-turned-shopkeeper action comedy" },
  ],
  "best-ongoing-manga-2026": [
    { name: "One Piece", bio: "Eiichiro Oda's pirate epic, in its final saga" },
    { name: "Kingdom", bio: "Yasuhisa Hara's sweeping Chinese-history war epic" },
    { name: "Grand Blue Dreaming", bio: "Kenji Inoue's riotous diving comedy" },
    { name: "Frieren: Beyond Journey's End", bio: "Kanehito Yamada's award-winning fantasy" },
    { name: "Oshi no Ko", bio: "Aka Akasaka's entertainment-industry drama" },
    { name: "Dandadan", bio: "Yukinobu Tatsu's ghosts-vs-aliens hit" },
    { name: "Kaiju No. 8", bio: "Naoya Matsumoto's kaiju defense force saga" },
    { name: "Sakamoto Days", bio: "Yuto Suzuki's retired-hitman action comedy" },
    { name: "Witch Hat Atelier", bio: "Kamome Shirahama's enchanting magic-school tale" },
    { name: "Medalist", bio: "Tsurumaikada's figure-skating drama" },
  ],
  "most-addictive-manga": [
    { name: "Solo Leveling", bio: "Chugong's Korean webtoon power-fantasy phenomenon" },
    { name: "Tower of God", bio: "SIU's Korean webtoon climbing epic" },
    { name: "Berserk", bio: "Kentaro Miura's dark fantasy masterpiece" },
    { name: "Vagabond", bio: "Takehiko Inoue's Miyamoto Musashi epic" },
    { name: "One Piece", bio: "Eiichiro Oda's endlessly bingeable pirate saga" },
    { name: "Death Note", bio: "Tsugumi Ohba's cat-and-mouse thriller" },
    { name: "Attack on Titan", bio: "Hajime Isayama's mystery-box blockbuster" },
    { name: "Chainsaw Man", bio: "Tatsuki Fujimoto's breakneck devil saga" },
    { name: "20th Century Boys", bio: "Naoki Urasawa's sprawling conspiracy epic" },
    { name: "Monster", bio: "Naoki Urasawa's psychological manhunt" },
  ],
  "most-overrated-manga-right-now": [
    { name: "Naruto", bio: "Masashi Kishimoto's ninja phenomenon" },
    { name: "Bleach", bio: "Tite Kubo's soul-reaper saga" },
    { name: "Sword Art Online", bio: "Reki Kawahara's VRMMO light-novel origin" },
    { name: "Tokyo Revengers", bio: "Ken Wakui's time-travel delinquent hit" },
    { name: "My Hero Academia", bio: "Kohei Horikoshi's superhero epic" },
    { name: "Demon Slayer", bio: "Koyoharu Gotouge's record-breaking hit" },
    { name: "Fairy Tail", bio: "Hiro Mashima's guild adventure" },
    { name: "Black Clover", bio: "Yuki Tabata's magic-knight shonen" },
    { name: "Boruto", bio: "The Naruto sequel series" },
    { name: "The Seven Deadly Sins", bio: "Nakaba Suzuki's fantasy adventure" },
  ],
  "most-underrated-manga": [
    { name: "Goodnight Punpun", bio: "Inio Asano's raw coming-of-age masterpiece" },
    { name: "Yokohama Kaidashi Kikou", bio: "Hitoshi Ashinano's quiet post-apocalyptic gem" },
    { name: "Planetes", bio: "Makoto Yukimura's hard-SF space-debris drama" },
    { name: "Historie", bio: "Hitoshi Iwaaki's ancient-Greece epic" },
    { name: "Dorohedoro", bio: "Q Hayashida's gloriously weird magic-noir" },
    { name: "Girls' Last Tour", bio: "Tsukumizu's gentle end-of-the-world journey" },
    { name: "Land of the Lustrous", bio: "Haruko Ichikawa's crystalline fantasy" },
    { name: "Witch Hat Atelier", bio: "Kamome Shirahama's beautiful magic-school tale" },
    { name: "Delicious in Dungeon", bio: "Ryoko Kui's dungeon-crawling food fantasy" },
    { name: "Showa Genroku Rakugo Shinju", bio: "Haruko Kumota's rakugo-period drama" },
  ],
  "manga-everyone-should-read-once": [
    { name: "Berserk", bio: "Kentaro Miura's dark fantasy landmark" },
    { name: "Vagabond", bio: "Takehiko Inoue's Musashi masterpiece" },
    { name: "Monster", bio: "Naoki Urasawa's definitive thriller" },
    { name: "20th Century Boys", bio: "Naoki Urasawa's mystery epic" },
    { name: "Pluto", bio: "Naoki Urasawa's Astro Boy reimagining" },
    { name: "Akira", bio: "Katsuhiro Otomo's cyberpunk landmark" },
    { name: "Lone Wolf and Cub", bio: "Kazuo Koike's samurai classic" },
    { name: "Phoenix", bio: "Osamu Tezuka's life-work epic" },
    { name: "Buddha", bio: "Osamu Tezuka's sweeping historical epic" },
    { name: "Fullmetal Alchemist", bio: "Hiromu Arakawa's perfectly complete classic" },
  ],
  "best-manga-for-anime-fans": [
    { name: "Berserk", bio: "The manga goes far beyond any adaptation" },
    { name: "Vagabond", bio: "No anime exists — the manga is the experience" },
    { name: "Kingdom", bio: "The manga's scale dwarfs its anime" },
    { name: "One Piece", bio: "Oda's pacing and art shine on the page" },
    { name: "Attack on Titan", bio: "Isayama's panels hit as hard as the anime" },
    { name: "Chainsaw Man", bio: "Fujimoto's kinetic art demands the manga" },
    { name: "Dorohedoro", bio: "Q Hayashida's world rewards close reading" },
    { name: "Land of the Lustrous", bio: "Ichikawa's art is best in print" },
    { name: "Witch Hat Atelier", bio: "Shirahama's detail needs the page" },
    { name: "Goodnight Punpun", bio: "Asano's masterpiece has no anime — by design" },
  ],
  "best-new-gen-manga": [
    { name: "Chainsaw Man", bio: "Tatsuki Fujimoto's genre-warping hit" },
    { name: "Jujutsu Kaisen", bio: "Gege Akutami's sorcery phenomenon" },
    { name: "Spy x Family", bio: "Tatsuya Endo's crossover smash" },
    { name: "Frieren: Beyond Journey's End", bio: "Kanehito Yamada's fantasy landmark" },
    { name: "Dandadan", bio: "Yukinobu Tatsu's occult sensation" },
    { name: "Kaiju No. 8", bio: "Naoya Matsumoto's monster blockbuster" },
    { name: "Sakamoto Days", bio: "Yuto Suzuki's action-comedy hit" },
    { name: "Oshi no Ko", bio: "Aka Akasaka's idol drama" },
    { name: "Blue Lock", bio: "Muneyuki Kaneshiro's ego-driven soccer saga" },
    { name: "Witch Hat Atelier", bio: "Kamome Shirahama's enchanting fantasy" },
  ],
  "manga-deserving-anime-adaptation": [
    { name: "Vagabond", bio: "Inoue's masterpiece still has no anime" },
    { name: "20th Century Boys", bio: "Urasawa's epic deserves a full adaptation" },
    { name: "Goodnight Punpun", bio: "Asano's story is famously unadapted" },
    { name: "Historie", bio: "Iwaaki's Greece epic awaits animation" },
    { name: "Yokohama Kaidashi Kikou", bio: "Only a short OVA exists of this classic" },
    { name: "Solanin", bio: "Asano's beloved music drama, unadapted" },
    { name: "Real", bio: "Takehiko Inoue's wheelchair-basketball drama" },
    { name: "Nausicaa of the Valley of the Wind", bio: "The manga's full story never got animated" },
    { name: "Fire Punch", bio: "Fujimoto's brutal early epic" },
    { name: "Abara", bio: "Tsutomu Nihei's white-gauna nightmare" },
  ],
  "best-manga-art-style": [
    { name: "Berserk", bio: "Miura's impossibly detailed dark fantasy art" },
    { name: "Vagabond", bio: "Inoue's brushwork masterpiece" },
    { name: "Blame!", bio: "Tsutomu Nihei's stark megastructure art" },
    { name: "Land of the Lustrous", bio: "Haruko Ichikawa's crystalline linework" },
    { name: "Witch Hat Atelier", bio: "Kamome Shirahama's intricate fantasy art" },
    { name: "Goodnight Punpun", bio: "Inio Asano's hyper-detailed realism" },
    { name: "Dorohedoro", bio: "Q Hayashida's gloriously grimy style" },
    { name: "Akira", bio: "Katsuhiro Otomo's dense cyberpunk detail" },
    { name: "Nausicaa of the Valley of the Wind", bio: "Miyazaki's lush watercolor epic" },
    { name: "Innocent", bio: "Shinichi Sakamoto's baroque French-revolution art" },
  ],
  "best-manga-panels": [
    { name: "Berserk", bio: "The Eclipse — manga's most infamous spread" },
    { name: "One Piece", bio: "\"Nothing happened\" — Zoro's iconic stand" },
    { name: "Attack on Titan", bio: "The Colossal Titan's first appearance" },
    { name: "Chainsaw Man", bio: "Fujimoto's explosive double spreads" },
    { name: "Vagabond", bio: "Musashi vs 70 men — the farming chapters' calm" },
    { name: "Slam Dunk", bio: "The final pass — wordless basketball poetry" },
    { name: "JoJo's Bizarre Adventure", bio: "Araki's legendary poses" },
    { name: "Demon Slayer", bio: "Hinokami Kagura's flowing spreads" },
    { name: "Gintama", bio: "Sorachi's perfect parody panels" },
    { name: "Kingdom", bio: "Shin's battlefield roars" },
  ],
  "best-manga-cover-art": [
    { name: "Chainsaw Man", bio: "Fujimoto's cinematic, homage-packed covers" },
    { name: "JoJo's Bizarre Adventure", bio: "Araki's fashion-magazine covers" },
    { name: "Berserk", bio: "Miura's haunting deluxe covers" },
    { name: "Dorohedoro", bio: "Q Hayashida's grimy, colorful chaos" },
    { name: "Land of the Lustrous", bio: "Ichikawa's jewel-like minimalism" },
    { name: "Witch Hat Atelier", bio: "Shirahama's storybook covers" },
    { name: "Goodnight Punpun", bio: "Asano's stark, symbolic designs" },
    { name: "Blame!", bio: "Nihei's imposing architectural covers" },
    { name: "Akira", bio: "Otomo's iconic red-and-black designs" },
    { name: "20th Century Boys", bio: "Urasawa's Friend-symbol covers" },
  ],
  "best-manga-character-design": [
    { name: "JoJo's Bizarre Adventure", bio: "Araki's fashion-icon character designs" },
    { name: "Bleach", bio: "Kubo's effortlessly stylish cast" },
    { name: "One Piece", bio: "Oda's endlessly inventive silhouettes" },
    { name: "Naruto", bio: "Kishimoto's iconic ninja designs" },
    { name: "My Hero Academia", bio: "Horikoshi's hero-costume creativity" },
    { name: "Black Butler", bio: "Yana Toboso's gothic elegance" },
    { name: "D.Gray-man", bio: "Katsura Hoshino's gothic designs" },
    { name: "Soul Eater", bio: "Atsushi Ohkubo's Halloween-inspired cast" },
    { name: "Fire Force", bio: "Ohkubo's firefighter-uniform flair" },
    { name: "Noragami", bio: "Adachitoka's sharp god-and-regalia designs" },
  ],
  "best-manga-protagonist": [
    { name: "Guts (Berserk)", bio: "The Black Swordsman's relentless struggle" },
    { name: "Miyamoto Musashi (Vagabond)", bio: "Inoue's search for invincibility's meaning" },
    { name: "Monkey D. Luffy (One Piece)", bio: "Freedom incarnate" },
    { name: "Eren Yeager (Attack on Titan)", bio: "From victim to the Rumbling itself" },
    { name: "Thorfinn (Vinland Saga)", bio: "Revenge to redemption across decades" },
    { name: "Ken Kaneki (Tokyo Ghoul)", bio: "The tragic half-ghoul transformation" },
    { name: "Denji (Chainsaw Man)", bio: "Fujimoto's gloriously ordinary devil" },
    { name: "Emma (The Promised Neverland)", bio: "The heart of the escape" },
    { name: "Senku Ishigami (Dr. Stone)", bio: "Science as superpower" },
    { name: "Punpun (Goodnight Punpun)", bio: "Asano's painfully real everyman" },
  ],
  "best-manga-villain": [
    { name: "Griffith (Berserk)", bio: "The Eclipse — betrayal incarnate" },
    { name: "Johan Liebert (Monster)", bio: "Urasawa's soft-spoken monster" },
    { name: "Meruem (Hunter x Hunter)", bio: "The king who learned humanity" },
    { name: "Madara Uchiha (Naruto)", bio: "The legendary Uchiha's return" },
    { name: "Sosuke Aizen (Bleach)", bio: "\"All part of my plan\"" },
    { name: "Muzan Kibutsuji (Demon Slayer)", bio: "The original demon's cruelty" },
    { name: "Tomura Shigaraki (My Hero Academia)", bio: "Decay given a tragic past" },
    { name: "Ryomen Sukuna (Jujutsu Kaisen)", bio: "The King of Curses' menace" },
    { name: "Frieza (Dragon Ball)", bio: "The galactic tyrant archetype" },
    { name: "Makima (Chainsaw Man)", bio: "Control itself, smiling" },
  ],
  "best-female-manga-character": [
    { name: "Mikasa Ackerman (Attack on Titan)", bio: "Humanity's strongest soldier" },
    { name: "Nico Robin (One Piece)", bio: "\"I want to live!\" — Enies Lobby" },
    { name: "Erza Scarlet (Fairy Tail)", bio: "Titania's unbreakable will" },
    { name: "Nezuko Kamado (Demon Slayer)", bio: "The demon who protects humans" },
    { name: "Nobara Kugisaki (Jujutsu Kaisen)", bio: "Unapologetically herself" },
    { name: "Kaguya Shinomiya (Kaguya-sama: Love Is War)", bio: "The ice queen's thaw" },
    { name: "Frieren (Frieren: Beyond Journey's End)", bio: "A thousand years learning grief" },
    { name: "Casca (Berserk)", bio: "The Hawks' sword, Miura's tragedy" },
    { name: "Revy (Black Lagoon)", bio: "\"Two Hands\" nihilism" },
    { name: "Yona (Yona of the Dawn)", bio: "Princess to warrior" },
  ],
  "best-manga-couple": [
    { name: "Guts & Casca (Berserk)", bio: "Love surviving the Eclipse" },
    { name: "Edward Elric & Winry Rockbell (Fullmetal Alchemist)", bio: "Alchemy's warmest ending" },
    { name: "Naruto Uzumaki & Hinata Hyuga (Naruto)", bio: "The shy girl's devotion rewarded" },
    { name: "Takeo Goda & Rinko Yamato (My Love Story!!)", bio: "Wholesome romance perfected" },
    { name: "Holo & Lawrence (Spice and Wolf)", bio: "Wit as love language" },
    { name: "Kosei Arima & Kaori Miyazono (Your Lie in April)", bio: "Music, spring, and loss" },
    { name: "Izumi Miyamura & Kyoko Hori (Horimiya)", bio: "Seeing each other's real selves" },
    { name: "Thorfinn & Gudrid (Vinland Saga)", bio: "Peace built together in Vinland" },
    { name: "Senku Ishigami & Kohaku (Dr. Stone)", bio: "Science and strength allied" },
    { name: "Yona & Hak (Yona of the Dawn)", bio: "Bodyguard to partner" },
  ],
  "best-manga-rivalry": [
    { name: "Naruto vs Sasuke (Naruto)", bio: "The Valley of the End, twice" },
    { name: "Goku vs Vegeta (Dragon Ball)", bio: "The eternal shonen rivalry" },
    { name: "Deku vs Bakugo (My Hero Academia)", bio: "From bullies to equals" },
    { name: "Light vs L (Death Note)", bio: "The battle of wits" },
    { name: "Gon vs Hisoka (Hunter x Hunter)", bio: "Predator and prey reversed" },
    { name: "Ippo vs Miyata (Hajime no Ippo)", bio: "The promised match" },
    { name: "Sakuragi vs Rukawa (Slam Dunk)", bio: "Rookie vs genius" },
    { name: "Yugi vs Kaiba (Yu-Gi-Oh!)", bio: "Heart of the cards vs money" },
    { name: "Eren vs Reiner (Attack on Titan)", bio: "Friends revealed as titans" },
    { name: "Kaneki vs Arima (Tokyo Ghoul)", bio: "The one-eyed king's duel" },
  ],
  "most-heartbreaking-manga": [
    { name: "Goodnight Punpun", bio: "Asano's devastating portrait of depression" },
    { name: "Solanin", bio: "Asano's quarter-life-crisis elegy" },
    { name: "A Silent Voice", bio: "Yoshitoki Oima's redemption story" },
    { name: "Banana Fish", bio: "Yoshida's tragic New York saga" },
    { name: "Ashita no Joe", bio: "Tetsuya Chiba's boxing tragedy" },
    { name: "Barefoot Gen", bio: "Keiji Nakazawa's Hiroshima memoir" },
    { name: "Your Lie in April", bio: "Naoshi Arakawa's musical farewell" },
    { name: "Orange", bio: "Ichigo Takano's letter from the future" },
    { name: "March Comes in Like a Lion", bio: "Chica Umino's quiet grief and shogi" },
    { name: "Fruits Basket", bio: "Natsuki Takaya's zodiac curse, healed" },
  ],
  "funniest-manga": [
    { name: "Gintama", bio: "Hideaki Sorachi's parody king" },
    { name: "Grand Blue Dreaming", bio: "Kenji Inoue's diving-club chaos" },
    { name: "Saiki K", bio: "Shuichi Aso's psychic straight-man comedy" },
    { name: "Nichijou", bio: "Keiichi Arawi's surreal school life" },
    { name: "Daily Lives of High School Boys", bio: "Yasunobu Yamauchi's deadpan classic" },
    { name: "Prison School", bio: "Akira Hiramoto's absurd ecchi comedy" },
    { name: "Cromartie High School", bio: "Eiji Nonaka's delinquent surrealism" },
    { name: "Bobobo-bo Bo-bobo", bio: "Yoshio Sawai's nose-hair nonsense" },
    { name: "Haven't You Heard? I'm Sakamoto", bio: "Nami Sano's impossibly cool gag manga" },
    { name: "Golden Kamuy", bio: "Satoru Noda's treasure hunt with perfect comic timing" },
  ],
  "darkest-manga-worth-reading": [
    { name: "Berserk", bio: "Miura's unflinching dark fantasy" },
    { name: "Goodnight Punpun", bio: "Asano's descent into despair" },
    { name: "Tokyo Ghoul", bio: "Sui Ishida's body-horror tragedy" },
    { name: "Uzumaki", bio: "Junji Ito's spiral of cosmic dread" },
    { name: "Homunculus", bio: "Hideo Yamamoto's trepanation nightmare" },
    { name: "Fire Punch", bio: "Fujimoto's bleakest epic" },
    { name: "Blame!", bio: "Nihei's silent megastructure horror" },
    { name: "Devilman", bio: "Go Nagai's apocalyptic classic" },
    { name: "Abara", bio: "Nihei's white-gauna carnage" },
    { name: "Franken Fran", bio: "Katsuhisa Kigitsu's surgical horror-comedy" },
  ],
  "best-romance-manga": [
    { name: "Horimiya", bio: "Hero's warm school romance" },
    { name: "Kaguya-sama: Love Is War", bio: "Aka Akasaka's battle-of-wits romance" },
    { name: "Your Lie in April", bio: "Naoshi Arakawa's bittersweet music romance" },
    { name: "Orange", bio: "Ichigo Takano's time-crossed love" },
    { name: "Ao Haru Ride", bio: "Io Sakisaka's first-love story" },
    { name: "Kimi ni Todoke", bio: "Karuho Shiina's gentle slow burn" },
    { name: "Wotakoi: Love Is Hard for Otaku", bio: "Fujita's adult otaku romance" },
    { name: "Fruits Basket", bio: "Natsuki Takaya's healing love story" },
    { name: "Nana", bio: "Ai Yazawa's messy, real romance" },
    { name: "Bloom Into You", bio: "Nio Nakatani's tender yuri classic" },
  ],
  "best-horror-manga": [
    { name: "Uzumaki", bio: "Junji Ito's spiral masterpiece" },
    { name: "Tomie", bio: "Ito's immortal femme fatale" },
    { name: "Gyo", bio: "Ito's fish-apocalypse nightmare" },
    { name: "The Drifting Classroom", bio: "Kazuo Umezu's survival horror classic" },
    { name: "Franken Fran", bio: "Katsuhisa Kigitsu's body-horror anthology" },
    { name: "Homunculus", bio: "Hideo Yamamoto's psychological horror" },
    { name: "I Am a Hero", bio: "Kengo Hanazawa's zombie epic" },
    { name: "Parasyte", bio: "Hitoshi Iwaaki's alien-invasion classic" },
    { name: "Hideout", bio: "Masasumi Kakizaki's island nightmare" },
    { name: "Fuan no Tane", bio: "Masaaki Nakayama's dread shorts" },
  ],
  "best-sports-manga": [
    { name: "Slam Dunk", bio: "Takehiko Inoue's basketball bible" },
    { name: "Haikyu!!", bio: "Haruichi Furudate's volleyball phenomenon" },
    { name: "Hajime no Ippo", bio: "George Morikawa's boxing epic" },
    { name: "Ashita no Joe", bio: "Tetsuya Chiba's tragic boxing classic" },
    { name: "Blue Lock", bio: "Muneyuki Kaneshiro's egoist soccer" },
    { name: "Kuroko's Basketball", bio: "Tadatoshi Fujimaki's superpower hoops" },
    { name: "Yowamushi Pedal", bio: "Wataru Watanabe's cycling saga" },
    { name: "Real", bio: "Takehiko Inoue's wheelchair-basketball drama" },
    { name: "Ping Pong", bio: "Taiyo Matsumoto's table-tennis art piece" },
    { name: "Ace of Diamond", bio: "Yuji Terajima's baseball epic" },
  ],
  "best-fantasy-manga": [
    { name: "Berserk", bio: "Miura's dark fantasy pinnacle" },
    { name: "Delicious in Dungeon", bio: "Ryoko Kui's inventive dungeon fantasy" },
    { name: "Witch Hat Atelier", bio: "Kamome Shirahama's magical world" },
    { name: "Frieren: Beyond Journey's End", bio: "Kanehito Yamada's post-hero fantasy" },
    { name: "Made in Abyss", bio: "Akihito Tsukushi's beautiful descent" },
    { name: "Dorohedoro", bio: "Q Hayashida's magic-noir chaos" },
    { name: "Claymore", bio: "Norihiro Yagi's silver-eyed warriors" },
    { name: "Magi", bio: "Shinobu Ohtaka's Arabian-nights adventure" },
    { name: "The Ancient Magus' Bride", bio: "Kore Yamazaki's faerie romance" },
    { name: "Nausicaa of the Valley of the Wind", bio: "Miyazaki's eco-fantasy epic" },
  ],
  "best-psychological-manga": [
    { name: "Monster", bio: "Urasawa's ultimate cat-and-mouse" },
    { name: "Death Note", bio: "Ohba and Obata's battle of wits" },
    { name: "Goodnight Punpun", bio: "Asano's psychological realism" },
    { name: "Homunculus", bio: "Yamamoto's perception horror" },
    { name: "20th Century Boys", bio: "Urasawa's conspiracy labyrinth" },
    { name: "Pluto", bio: "Urasawa's robot-murder mystery" },
    { name: "Liar Game", bio: "Shinobu Kaitani's game-theory thriller" },
    { name: "Kaiji", bio: "Nobuyuki Fukumoto's gambling despair" },
    { name: "Tomodachi Game", bio: "Mikoto Yamaguchi's friendship trials" },
    { name: "The Promised Neverland", bio: "Kaiu Shirai's escape puzzle" },
  ],
  "best-manga-plot-twist": [
    { name: "The basement reveal (Attack on Titan)", bio: "The world's true history, hidden for decades" },
    { name: "Johan's true nature (Monster)", bio: "The boy Tenma saved was the monster" },
    { name: "Itachi's truth (Naruto)", bio: "The villain was the village's greatest protector" },
    { name: "The Eclipse (Berserk)", bio: "Griffith's sacrifice of the Band of the Hawk" },
    { name: "L's successors (Death Note)", bio: "Near and Mello pick up the hunt" },
    { name: "The farm's secret (The Promised Neverland)", bio: "The orphanage is a demon farm" },
    { name: "Reiner is the Armored Titan (Attack on Titan)", bio: "The reveal that broke the fandom" },
    { name: "Aizen's betrayal (Bleach)", bio: "The kind captain's century-long plan" },
    { name: "Meruem's end (Hunter x Hunter)", bio: "The king dies playing gungi" },
    { name: "Punpun's ending (Goodnight Punpun)", bio: "Asano's bleak, ambiguous farewell" },
  ],
  "manga-best-worldbuilding": [
    { name: "One Piece", bio: "Oda's 25 years of interconnected seas" },
    { name: "Attack on Titan", bio: "Isayama's walls hiding a world" },
    { name: "Made in Abyss", bio: "Tsukushi's layered, lethal pit" },
    { name: "Dorohedoro", bio: "Q Hayashida's Hole and sorcerer world" },
    { name: "Blame!", bio: "Nihei's endless megastructure" },
    { name: "Nausicaa of the Valley of the Wind", bio: "Miyazaki's toxic jungle ecology" },
    { name: "Land of the Lustrous", bio: "Ichikawa's far-future gem world" },
    { name: "Delicious in Dungeon", bio: "Kui's dungeon as ecosystem" },
    { name: "Witch Hat Atelier", bio: "Shirahama's rule-bound magic" },
    { name: "Girls' Last Tour", bio: "Tsukumizu's quiet ruined world" },
  ],
  "manga-read-first-time": [
    { name: "One Piece", bio: "The adventure everyone should take fresh" },
    { name: "Berserk", bio: "Miura's journey, best unspoiled" },
    { name: "Vagabond", bio: "Musashi's path, best walked blind" },
    { name: "Fullmetal Alchemist", bio: "Arakawa's perfect plot, worth re-experiencing" },
    { name: "20th Century Boys", bio: "Urasawa's mystery, best unsolved" },
    { name: "Goodnight Punpun", bio: "Asano's gut-punch, once is enough" },
    { name: "Slam Dunk", bio: "Inoue's final match, best felt live" },
    { name: "Monster", bio: "The hunt for Johan, best unspoiled" },
    { name: "Kingdom", bio: "Hara's wars, best witnessed firsthand" },
    { name: "Yona of the Dawn", bio: "Kusanagi's slow-burn epic" },
  ],
};

export async function attachMangaNominees(): Promise<void> {
  try {
    const team = await findUserByEmail(TEAM_EMAIL);
    if (!team) return;
    for (const [slug, nominees] of Object.entries(MANGA_NOMINEES)) {
      // Slug first, exact-title fallback (reused rows keep original slugs).
      const rankingId = await findRequiredRankingId(slug);
      if (!rankingId) continue;
      for (const n of nominees) {
        const dupe = await findNomineeByRankingAndName(rankingId, n.name);
        if (dupe) continue;
        await createProfile({
          rankingId,
          name: n.name,
          bio: n.bio ?? "",
          addedBy: team.id,
        });
      }
    }
  } catch {
    // best-effort: never break startup
  }
}
