// -----------------------------------------------------------------------
// Gaming nominee sets (2026-09-30): 10 factual nominees for each of the 29
// Gaming cluster rankings (excluding best-game-of-all-time, which already
// has its set in seedFlagshipNominees.ts). All entities are real, well-known
// video games, characters, worlds or fights — never invented, never real
// people. Idempotent: matched by (ranking_id, name); existing rows are
// never duplicated. Runs after the required-ranking seeds in
// ensureMigrated(). Never throws.
// -----------------------------------------------------------------------
import { findUserByEmail } from "./users";
import { createProfile, findNomineeByRankingAndName } from "./profiles";
import { findRequiredRankingId } from "./seedFlagshipNominees";

const TEAM_EMAIL = "team@rephear.com";

const GAMING_NOMINEES: Record<string, { name: string; bio: string }[]> = {
  "best-game-right-now": [
    { name: "Baldur's Gate 3", bio: "2023 CRPG triumph, still dominating" },
    { name: "Elden Ring", bio: "2022 open-world epic, Nightreign spinoff in 2025" },
    { name: "Grand Theft Auto V", bio: "2013 Rockstar's eternal bestseller" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Fortnite", bio: "The live-service phenomenon" },
    { name: "Helldivers 2", bio: "2024 co-op breakout hit" },
    { name: "Black Myth: Wukong", bio: "2024 action-RPG phenomenon" },
    { name: "The Legend of Zelda: Tears of the Kingdom", bio: "2023 Nintendo's open-world marvel" },
    { name: "God of War Ragnarök", bio: "2022 Norse saga finale" },
    { name: "Cyberpunk 2077", bio: "Redeemed by Phantom Liberty, 2023" },
  ],
  "game-of-the-year-2026": [
    { name: "Baldur's Gate 3", bio: "2023 CRPG triumph, still in the conversation" },
    { name: "Elden Ring", bio: "2022 FromSoftware's open-world epic" },
    { name: "The Legend of Zelda: Tears of the Kingdom", bio: "2023 Nintendo's open-world marvel" },
    { name: "God of War Ragnarök", bio: "2022 Norse saga finale" },
    { name: "Black Myth: Wukong", bio: "2024 action-RPG phenomenon" },
    { name: "Helldivers 2", bio: "2024 co-op breakout hit" },
    { name: "Astro Bot", bio: "2024 platforming joy, actual 2024 GOTY winner" },
    { name: "Metaphor: ReFantazio", bio: "2024 Atlus RPG" },
    { name: "Tekken 8", bio: "2024 fighting-game benchmark" },
    { name: "Hades II", bio: "Supergiant's roguelike sequel, early access 2024" },
  ],
  "most-overrated-game-right-now": [
    { name: "Grand Theft Auto V", bio: "2013 Rockstar's eternal bestseller" },
    { name: "Fortnite", bio: "The live-service phenomenon" },
    { name: "Call of Duty: Warzone", bio: "Free-to-play battle royale juggernaut" },
    { name: "EA Sports FC 24", bio: "Annual football sim, successor to FIFA" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Overwatch 2", bio: "Blizzard's hero shooter sequel" },
    { name: "Cyberpunk 2077", bio: "2020's most notorious launch" },
    { name: "Starfield", bio: "2023 Bethesda space epic" },
    { name: "Diablo IV", bio: "2023 Blizzard's dungeon crawler" },
    { name: "Pokémon Scarlet & Violet", bio: "2022's divisive open-world Pokémon" },
  ],
  "most-underrated-game": [
    { name: "Outer Wilds", bio: "2019 exploration mystery, a masterpiece" },
    { name: "Disco Elysium", bio: "2019 RPG of pure writing" },
    { name: "Hollow Knight", bio: "2017 metroidvania perfection" },
    { name: "Hades", bio: "2020 roguelike by Supergiant" },
    { name: "Celeste", bio: "2018 precision platformer with heart" },
    { name: "Return of the Obra Dinn", bio: "2018 deduction puzzle on a ghost ship" },
    { name: "Slay the Spire", bio: "2019 deckbuilding roguelike" },
    { name: "Factorio", bio: "2020 automation obsession" },
    { name: "RimWorld", bio: "2018 colony sim storytelling engine" },
    { name: "Prey (2017)", bio: "Arkane's immersive sim, criminally overlooked" },
  ],
  "your-forever-game": [
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Tetris", bio: "1984 the eternal puzzle" },
    { name: "The Elder Scrolls V: Skyrim", bio: "2011 open-world RPG by Bethesda" },
    { name: "Grand Theft Auto V", bio: "2013 Rockstar's eternal bestseller" },
    { name: "The Witcher 3: Wild Hunt", bio: "2015 RPG landmark" },
    { name: "Portal 2", bio: "2011 puzzle perfection" },
    { name: "Half-Life 2", bio: "2004 FPS revolution" },
    { name: "Chrono Trigger", bio: "1995 JRPG time-travel classic" },
    { name: "Super Mario 64", bio: "1996 3D platforming blueprint" },
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
  ],
  "game-play-first-time": [
    { name: "Outer Wilds", bio: "2019 exploration mystery, a masterpiece" },
    { name: "Portal 2", bio: "2011 puzzle perfection" },
    { name: "Red Dead Redemption 2", bio: "2018 Rockstar's western epic" },
    { name: "The Last of Us", bio: "2013 Naughty Dog's survival drama" },
    { name: "BioShock", bio: "2007 Rapture's underwater dystopia" },
    { name: "Subnautica", bio: "2018 underwater survival wonder" },
    { name: "Elden Ring", bio: "2022 FromSoftware's open-world epic" },
    { name: "Undertale", bio: "2015 indie RPG by Toby Fox" },
    { name: "Firewatch", bio: "2016 Wyoming wilderness mystery" },
    { name: "What Remains of Edith Finch", bio: "2017 interactive family tragedy" },
  ],
  "most-addictive-game": [
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Fortnite", bio: "The live-service phenomenon" },
    { name: "League of Legends", bio: "The world's biggest MOBA" },
    { name: "World of Warcraft", bio: "2004's MMO that never dies" },
    { name: "Civilization VI", bio: "One-more-turn strategy king" },
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
    { name: "Rocket League", bio: "Soccer with rocket cars" },
    { name: "Apex Legends", bio: "Respawn's hero battle royale" },
    { name: "Diablo III", bio: "2012 loot-grind perfection" },
    { name: "Slay the Spire", bio: "2019 deckbuilding roguelike" },
  ],
  "best-multiplayer-game": [
    { name: "Fortnite", bio: "The live-service phenomenon" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Rocket League", bio: "Soccer with rocket cars" },
    { name: "Among Us", bio: "2020 social deduction hit" },
    { name: "Fall Guys", bio: "Chaotic bean battle royale" },
    { name: "Apex Legends", bio: "Respawn's hero battle royale" },
    { name: "Overwatch 2", bio: "Blizzard's hero shooter sequel" },
    { name: "Grand Theft Auto Online", bio: "Rockstar's persistent crime sandbox" },
    { name: "Sea of Thieves", bio: "Rare's pirate adventure" },
    { name: "Deep Rock Galactic", bio: "Dwarven co-op mining shooter" },
  ],
  "best-co-op-game": [
    { name: "It Takes Two", bio: "2021 GOTY co-op adventure" },
    { name: "Portal 2", bio: "2011 puzzle perfection, co-op included" },
    { name: "Deep Rock Galactic", bio: "Dwarven co-op mining shooter" },
    { name: "Left 4 Dead 2", bio: "2009 zombie co-op classic" },
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
    { name: "A Way Out", bio: "2018 prison-break co-op story" },
    { name: "Overcooked! 2", bio: "Chaotic kitchen co-op" },
    { name: "Diablo IV", bio: "2023 Blizzard's dungeon crawler" },
    { name: "Baldur's Gate 3", bio: "2023 CRPG triumph" },
    { name: "Sea of Thieves", bio: "Rare's pirate adventure" },
  ],
  "best-competitive-game": [
    { name: "League of Legends", bio: "The world's biggest MOBA" },
    { name: "Counter-Strike 2", bio: "Valve's tactical FPS standard" },
    { name: "Valorant", bio: "Riot's tactical hero shooter" },
    { name: "Dota 2", bio: "Valve's deep MOBA" },
    { name: "Rocket League", bio: "Soccer with rocket cars" },
    { name: "Street Fighter 6", bio: "2023 fighting-game revival" },
    { name: "Tekken 8", bio: "2024 fighting-game benchmark" },
    { name: "StarCraft II", bio: "Blizzard's RTS esports pillar" },
    { name: "Rainbow Six Siege", bio: "Ubisoft's tactical shooter" },
    { name: "Apex Legends", bio: "Respawn's hero battle royale" },
  ],
  "best-open-world-game": [
    { name: "Elden Ring", bio: "2022 FromSoftware's open-world epic" },
    { name: "The Legend of Zelda: Breath of the Wild", bio: "2017 open-world reinvention" },
    { name: "Red Dead Redemption 2", bio: "2018 Rockstar's western epic" },
    { name: "Grand Theft Auto V", bio: "2013 Rockstar's eternal bestseller" },
    { name: "The Witcher 3: Wild Hunt", bio: "2015 RPG landmark" },
    { name: "The Elder Scrolls V: Skyrim", bio: "2011 open-world RPG by Bethesda" },
    { name: "Ghost of Tsushima", bio: "2020 samurai epic" },
    { name: "Horizon Zero Dawn", bio: "2017 Guerrilla's machine-hunting world" },
    { name: "Marvel's Spider-Man 2", bio: "2023 Insomniac's web-swinging sequel" },
    { name: "Cyberpunk 2077", bio: "Night City's neon sprawl" },
  ],
  "best-rpg": [
    { name: "Baldur's Gate 3", bio: "2023 CRPG triumph" },
    { name: "Elden Ring", bio: "2022 FromSoftware's open-world epic" },
    { name: "The Witcher 3: Wild Hunt", bio: "2015 RPG landmark" },
    { name: "The Elder Scrolls V: Skyrim", bio: "2011 open-world RPG by Bethesda" },
    { name: "Persona 5 Royal", bio: "2019 Atlus JRPG masterpiece" },
    { name: "Final Fantasy VII Remake", bio: "2020's Midgar reimagined" },
    { name: "Divinity: Original Sin 2", bio: "2017 CRPG benchmark" },
    { name: "Mass Effect 2", bio: "2010 BioWare's space opera peak" },
    { name: "Disco Elysium", bio: "2019 RPG of pure writing" },
    { name: "Chrono Trigger", bio: "1995 JRPG time-travel classic" },
  ],
  "best-horror-game": [
    { name: "Resident Evil 4 (Remake)", bio: "2023 survival-horror remake" },
    { name: "Silent Hill 2 (Remake)", bio: "2024 Bloober Team's faithful remake" },
    { name: "Amnesia: The Dark Descent", bio: "2010 first-person horror landmark" },
    { name: "Outlast", bio: "2013 found-footage asylum terror" },
    { name: "Alien: Isolation", bio: "2014 stealth horror perfection" },
    { name: "Dead Space (Remake)", bio: "2023 sci-fi horror remake" },
    { name: "The Evil Within 2", bio: "2017 Shinji Mikami's nightmare" },
    { name: "Visage", bio: "2020 psychological horror indie" },
    { name: "Phasmophobia", bio: "2020 co-op ghost hunting" },
    { name: "Until Dawn", bio: "2015 cinematic teen horror" },
  ],
  "best-indie-game": [
    { name: "Hollow Knight", bio: "2017 metroidvania perfection" },
    { name: "Hades", bio: "2020 roguelike by Supergiant" },
    { name: "Celeste", bio: "2018 precision platformer with heart" },
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
    { name: "Undertale", bio: "2015 indie RPG by Toby Fox" },
    { name: "Outer Wilds", bio: "2019 exploration mystery, a masterpiece" },
    { name: "Disco Elysium", bio: "2019 RPG of pure writing" },
    { name: "Slay the Spire", bio: "2019 deckbuilding roguelike" },
    { name: "Balatro", bio: "2024 poker roguelike phenomenon" },
    { name: "Vampire Survivors", bio: "2022 bullet-heaven indie hit" },
  ],
  "best-cozy-game": [
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
    { name: "Animal Crossing: New Horizons", bio: "2020 island-life phenomenon" },
    { name: "Spiritfarer", bio: "2020 gentle game about death" },
    { name: "A Short Hike", bio: "2019 tiny mountain adventure" },
    { name: "Unpacking", bio: "2021 storytelling through boxes" },
    { name: "PowerWash Simulator", bio: "2022 oddly satisfying cleaning" },
    { name: "Disney Dreamlight Valley", bio: "2022 life-sim with Disney magic" },
    { name: "Coral Island", bio: "2023 tropical farming sim" },
    { name: "Dave the Diver", bio: "2023 diving-and-sushi indie hit" },
    { name: "Coffee Talk", bio: "2020 late-night café visual novel" },
  ],
  "best-story-in-gaming": [
    { name: "Red Dead Redemption 2", bio: "2018 Rockstar's western epic" },
    { name: "The Last of Us", bio: "2013 Naughty Dog's survival drama" },
    { name: "BioShock", bio: "2007 Rapture's underwater dystopia" },
    { name: "Portal 2", bio: "2011 puzzle perfection" },
    { name: "Disco Elysium", bio: "2019 RPG of pure writing" },
    { name: "Outer Wilds", bio: "2019 exploration mystery, a masterpiece" },
    { name: "God of War (2018)", bio: "Norse reboot of Kratos' saga" },
    { name: "Mass Effect 2", bio: "2010 BioWare's space opera peak" },
    { name: "To the Moon", bio: "2011 indie tearjerker" },
    { name: "What Remains of Edith Finch", bio: "2017 interactive family tragedy" },
  ],
  "best-game-world": [
    { name: "The Lands Between (Elden Ring)", bio: "FromSoftware's haunting open world" },
    { name: "Hyrule (The Legend of Zelda: Breath of the Wild)", bio: "Nintendo's reinvention of exploration" },
    { name: "Tamriel (The Elder Scrolls V: Skyrim)", bio: "Bethesda's northern fantasy realm" },
    { name: "The American Frontier (Red Dead Redemption 2)", bio: "Rockstar's living 1899 west" },
    { name: "Rapture (BioShock)", bio: "Art-deco underwater dystopia" },
    { name: "Planet 4546B (Subnautica)", bio: "An entire ocean to survive" },
    { name: "Hallownest (Hollow Knight)", bio: "A fallen insect kingdom" },
    { name: "The Solar System (Outer Wilds)", bio: "22 minutes to explore everything" },
    { name: "Tsushima Island (Ghost of Tsushima)", bio: "Feudal Japan in painterly detail" },
    { name: "Night City (Cyberpunk 2077)", bio: "Neon-drenched dystopian sprawl" },
  ],
  "best-video-game-character": [
    { name: "Mario", bio: "Nintendo's mascot since 1981" },
    { name: "Link", bio: "Hero of Hyrule" },
    { name: "Master Chief", bio: "Halo's Spartan-117" },
    { name: "Kratos", bio: "God of War's ghost of Sparta" },
    { name: "Geralt of Rivia", bio: "The Witcher's white wolf" },
    { name: "Lara Croft", bio: "Tomb Raider's icon" },
    { name: "Arthur Morgan", bio: "Red Dead Redemption 2's outlaw" },
    { name: "Ellie", bio: "The Last of Us' survivor" },
    { name: "Nathan Drake", bio: "Uncharted's treasure hunter" },
    { name: "Pikachu", bio: "Pokémon's electric mascot" },
  ],
  "best-gaming-villain": [
    { name: "GLaDOS (Portal)", bio: "Passive-aggressive AI overlord" },
    { name: "Sephiroth (Final Fantasy VII)", bio: "The one-winged angel" },
    { name: "Ganondorf (The Legend of Zelda)", bio: "Hyrule's eternal nemesis" },
    { name: "Vaas Montenegro (Far Cry 3)", bio: "The definition of insanity" },
    { name: "Handsome Jack (Borderlands 2)", bio: "Charismatic corporate tyrant" },
    { name: "The Lich King (Warcraft)", bio: "Arthas, king of the undead" },
    { name: "Andrew Ryan (BioShock)", bio: "Rapture's objectivist founder" },
    { name: "Dutch van der Linde (Red Dead Redemption 2)", bio: "Charisma curdling into madness" },
    { name: "SHODAN (System Shock)", bio: "Gaming's original rogue AI" },
    { name: "Pyramid Head (Silent Hill)", bio: "Horror's most iconic monster" },
  ],
  "best-video-game-duo": [
    { name: "Mario & Luigi", bio: "Nintendo's plumber brothers" },
    { name: "Ratchet & Clank", bio: "Lombax and robot duo" },
    { name: "Jak & Daxter", bio: "Naughty Dog's odd couple" },
    { name: "Banjo & Kazooie", bio: "Bear and bird platforming pair" },
    { name: "Master Chief & Cortana", bio: "Halo's Spartan and AI" },
    { name: "Joel & Ellie", bio: "The Last of Us' survivors" },
    { name: "Booker & Elizabeth", bio: "BioShock Infinite's duo" },
    { name: "Drake & Sully", bio: "Uncharted's mentor and protégé" },
    { name: "Kratos & Atreus", bio: "God of War's father and son" },
    { name: "Cody & May", bio: "It Takes Two's co-op couple" },
  ],
  "best-video-game-romance": [
    { name: "Geralt & Yennefer", bio: "The Witcher 3's sorceress and witcher" },
    { name: "Tidus & Yuna", bio: "Final Fantasy X's star-crossed pair" },
    { name: "Cloud & Tifa", bio: "Final Fantasy VII's childhood bond" },
    { name: "Drake & Elena", bio: "Uncharted's adventuring couple" },
    { name: "Shepard & Liara", bio: "Mass Effect's cross-species romance" },
    { name: "Mario & Princess Peach", bio: "Gaming's oldest rescue romance" },
    { name: "Link & Zelda", bio: "Hyrule's eternal bond" },
    { name: "Max & Chloe", bio: "Life Is Strange's inseparable friends" },
    { name: "Garrus & Tali", bio: "Mass Effect's fan-favourite pairing" },
    { name: "Zidane & Garnet", bio: "Final Fantasy IX's thief and princess" },
  ],
  "best-game-soundtrack": [
    { name: "The Elder Scrolls V: Skyrim", bio: "Jeremy Soule's sweeping score" },
    { name: "DOOM (2016)", bio: "Mick Gordon's metal onslaught" },
    { name: "Hollow Knight", bio: "Christopher Larkin's haunting score" },
    { name: "NieR: Automata", bio: "Keiichi Okabe's ethereal soundtrack" },
    { name: "Final Fantasy VII", bio: "Nobuo Uematsu's legendary score" },
    { name: "Persona 5", bio: "Shoji Meguro's acid-jazz style" },
    { name: "The Legend of Zelda: Ocarina of Time", bio: "Koji Kondo's timeless melodies" },
    { name: "Undertale", bio: "Toby Fox's chiptune emotion" },
    { name: "Red Dead Redemption 2", bio: "Woody Jackson's western score" },
    { name: "Outer Wilds", bio: "Andrew Prahlow's cosmic folk" },
  ],
  "best-character-design-gaming": [
    { name: "Overwatch 2", bio: "Blizzard's instantly readable hero roster" },
    { name: "League of Legends", bio: "Riot's ever-expanding champion lineup" },
    { name: "Final Fantasy XIV", bio: "Square Enix's stylish MMO cast" },
    { name: "The Legend of Zelda: Breath of the Wild", bio: "Nintendo's expressive Hyrule" },
    { name: "Persona 5", bio: "Shigenori Soejima's sharp style" },
    { name: "Street Fighter 6", bio: "Capcom's bold fighter redesigns" },
    { name: "Genshin Impact", bio: "HoYoverse's anime-inspired cast" },
    { name: "Apex Legends", bio: "Respawn's diverse legend roster" },
    { name: "Hollow Knight", bio: "Team Cherry's insect world" },
    { name: "Hades", bio: "Supergiant's godly art direction" },
  ],
  "best-boss-fight-of-all-time": [
    { name: "Ornstein & Smough (Dark Souls)", bio: "2011's legendary duo" },
    { name: "Malenia, Blade of Miquella (Elden Ring)", bio: "2022's infamous duel" },
    { name: "Sword Saint Isshin (Sekiro)", bio: "2019's ultimate test" },
    { name: "Mantis Lords (Hollow Knight)", bio: "2017's graceful duel" },
    { name: "Sans (Undertale)", bio: "2015's hardest joke" },
    { name: "Psycho Mantis (Metal Gear Solid)", bio: "1998's fourth-wall breaker" },
    { name: "Sephiroth (Kingdom Hearts)", bio: "2002's secret superboss" },
    { name: "Ganon (The Legend of Zelda: Ocarina of Time)", bio: "1998's castle finale" },
    { name: "Knight Artorias (Dark Souls)", bio: "2012's tragic duel" },
    { name: "Ludwig, the Holy Blade (Bloodborne)", bio: "2015's two-phase nightmare" },
  ],
  "hardest-game-you-love": [
    { name: "Dark Souls", bio: "2011 the modern action-RPG template" },
    { name: "Sekiro: Shadows Die Twice", bio: "2019 FromSoftware's parry masterclass" },
    { name: "Elden Ring", bio: "2022 FromSoftware's open-world epic" },
    { name: "Celeste", bio: "2018 precision platformer with heart" },
    { name: "Hollow Knight", bio: "2017 metroidvania perfection" },
    { name: "Cuphead", bio: "2017 run-and-gun boss gauntlet" },
    { name: "Super Meat Boy", bio: "2010 precision platforming pain" },
    { name: "Bloodborne", bio: "2015 gothic action horror" },
    { name: "Returnal", bio: "2021 Housemarque's roguelike shooter" },
    { name: "Hades", bio: "2020 roguelike by Supergiant" },
  ],
  "best-game-with-friends": [
    { name: "Mario Kart 8 Deluxe", bio: "Nintendo's party racing king" },
    { name: "Super Smash Bros. Ultimate", bio: "2018's everyone-is-here brawler" },
    { name: "Overcooked! 2", bio: "Chaotic kitchen co-op" },
    { name: "The Jackbox Party Packs", bio: "Phone-based party games" },
    { name: "Among Us", bio: "2020 social deduction hit" },
    { name: "Fall Guys", bio: "Chaotic bean battle royale" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "It Takes Two", bio: "2021 GOTY co-op adventure" },
    { name: "Rocket League", bio: "Soccer with rocket cars" },
    { name: "Keep Talking and Nobody Explodes", bio: "Co-op bomb defusal" },
  ],
  "game-best-community": [
    { name: "Final Fantasy XIV", bio: "Square Enix's famously welcoming MMO" },
    { name: "Deep Rock Galactic", bio: "Rock and stone, wholesome dwarves" },
    { name: "Warframe", bio: "Digital Extremes' loyal tenno" },
    { name: "Stardew Valley", bio: "2016 farming sim by ConcernedApe" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Destiny 2", bio: "Bungie's sci-fi shooter community" },
    { name: "Guild Wars 2", bio: "ArenaNet's cooperative MMO" },
    { name: "Helldivers 2", bio: "2024 co-op breakout hit" },
    { name: "No Man's Sky", bio: "Hello Games' redemption story" },
    { name: "Terraria", bio: "2011 sandbox adventure" },
  ],
  "game-most-chaotic-community": [
    { name: "League of Legends", bio: "The world's biggest MOBA" },
    { name: "Grand Theft Auto Online", bio: "Rockstar's persistent crime sandbox" },
    { name: "Rust", bio: "Facepunch's brutal survival" },
    { name: "DayZ", bio: "Bohemia's zombie survival chaos" },
    { name: "EVE Online", bio: "CCP's player-driven space politics" },
    { name: "Fortnite", bio: "The live-service phenomenon" },
    { name: "Call of Duty", bio: "Activision's FPS juggernaut" },
    { name: "Roblox", bio: "The user-generated universe" },
    { name: "ARK: Survival Evolved", bio: "Dinosaur survival mayhem" },
    { name: "Dead by Daylight", bio: "Behaviour's asymmetric horror" },
  ],
  "game-defined-childhood": [
    { name: "Super Mario 64", bio: "1996 3D platforming blueprint" },
    { name: "Pokémon Red & Blue", bio: "1996 Game Boy phenomenon" },
    { name: "The Legend of Zelda: Ocarina of Time", bio: "1998's timeless adventure" },
    { name: "Minecraft", bio: "Best-selling game of all time" },
    { name: "Tetris", bio: "1984 the eternal puzzle" },
    { name: "Sonic the Hedgehog 2", bio: "1992 Sega's speed classic" },
    { name: "Crash Bandicoot", bio: "1996 PlayStation mascot" },
    { name: "Spyro the Dragon", bio: "1998 purple dragon adventure" },
    { name: "Halo: Combat Evolved", bio: "2001 Xbox's defining shooter" },
    { name: "The Sims", bio: "2000 life-sim phenomenon" },
  ],
};

export async function attachGamingNominees(): Promise<void> {
  try {
    const team = await findUserByEmail(TEAM_EMAIL);
    if (!team) return;
    for (const [slug, nominees] of Object.entries(GAMING_NOMINEES)) {
      // Slug first, exact-title fallback (reused rows keep original slugs).
      const rankingId = await findRequiredRankingId(slug);
      if (!rankingId) continue;
      for (const n of nominees) {
        const dupe = await findNomineeByRankingAndName(rankingId, n.name);
        if (dupe) continue;
        await createProfile({
          rankingId,
          name: n.name,
          bio: n.bio ?? "",
          addedBy: team.id,
        });
      }
    }
  } catch {
    // Best-effort seed step: never break startup.
  }
}
