import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createUser } from "../src/db/users";
import { ensureMigrated } from "../src/db/schema";
import { findEventPerson, findSocialEvent, getEventPersonConnections, listEventPeople, recognizePerson, upsertSelfAtEvent } from "../src/db/events";
import { safeNextPath } from "../src/lib/safeNextPath";
import { normalizeSocialProfileUrl } from "../src/lib/socialProfileUrl";
import { eventRecognitionEmail } from "../src/emails/eventRecognition";
import { eventMessageEmail } from "../src/emails/eventMessage";
import { getEventConversation, getOrCreateEventConversation, listEventConversations, listUserEventConversations, sendEventMessage } from "../src/db/eventMessages";

async function run() {
  await ensureMigrated();
  await ensureMigrated();
  const event = await findSocialEvent("animecon-london-2026");
  assert(event, "published AnimeCon event is seeded idempotently");
  const a = await createUser({ email: "event-a@example.test", passwordHash: "x", name: "Alice" });
  const b = await createUser({ email: "event-b@example.test", passwordHash: "x", name: "Bob" });
  const c = await createUser({ email: "event-c@example.test", passwordHash: "x", name: "Cara" });
  const alice = await upsertSelfAtEvent({ eventId: event.id, userId: a.id, displayName: "Alice", photoUrl: "https://example.test/a.jpg", identities: ["Artist"], fandomTags: ["Frieren"], sayHi: "Hello", instagramUrl: "", tiktokUrl: "" });
  const aliceSecondCard = await upsertSelfAtEvent({ eventId: event.id, userId: a.id, displayName: "Alice Cosplay", photoUrl: "https://example.test/a2.jpg", identities: ["Cosplayer"], fandomTags: ["Frieren"], sayHi: "Second look", instagramUrl: "", tiktokUrl: "" });
  assert.notEqual(aliceSecondCard, alice, "one account can create multiple independent cards");
  const bob = await upsertSelfAtEvent({ eventId: event.id, userId: b.id, displayName: "Bob", photoUrl: "https://example.test/b.jpg", identities: ["Cosplayer"], fandomTags: ["One Piece"], sayHi: "Hi", instagramUrl: "", tiktokUrl: "" });
  const cara = await upsertSelfAtEvent({ eventId: event.id, userId: c.id, displayName: "Cara", photoUrl: "https://example.test/c.jpg", identities: ["Creator"], fandomTags: ["Manga"], sayHi: "Hey", instagramUrl: "", tiktokUrl: "" });
  assert.equal(await recognizePerson(event.id, a.id, alice), "self");
  assert.equal(await recognizePerson(event.id, a.id, bob), "created");
  assert.equal(await recognizePerson(event.id, a.id, bob), "exists");
  assert.equal(await recognizePerson(event.id, b.id, alice), "mutual");
  const conversationId = await getOrCreateEventConversation(event.id, a.id, b.id);
  assert.equal(await getOrCreateEventConversation(event.id, b.id, a.id), conversationId, "a mutual pair shares one conversation");
  await sendEventMessage(conversationId, event.id, a.id, "Hello Bob ✦");
  const conversation = await getEventConversation(conversationId, event.id, b.id);
  assert.equal(conversation?.messages[0]?.body, "Hello Bob ✦", "mutual users can exchange messages");
  assert.equal((await listEventConversations(event.id, b.id))[0]?.id, conversationId, "conversation appears in the event inbox");
  const profileInbox = await listUserEventConversations(b.id);
  assert.equal(profileInbox[0]?.id, conversationId, "conversation appears on the account owner's main profile");
  assert.equal(profileInbox[0]?.eventSlug, "animecon-london-2026", "profile conversation retains its event destination");
  await assert.rejects(() => getOrCreateEventConversation(event.id, a.id, c.id), /mutual recognition/, "one-way recognition cannot open chat");
  assert.equal(await recognizePerson(event.id, b.id, cara), "created");
  const people = await listEventPeople(event.id, a.id);
  assert.equal(people.filter((person) => person.userId === a.id).length, 2, "both cards remain visible");
  const bobForAlice = people.find((p) => p.id === bob);
  assert.equal(bobForAlice?.recognizedBy, 1);
  assert.equal(bobForAlice?.recognized, true);
  assert.equal(bobForAlice?.mutual, true);
  assert.deepEqual(bobForAlice?.fandomTags, ["One Piece"]);
  const bobProfile = await findEventPerson(bob, a.id);
  assert(bobProfile);
  const bobConnections = await getEventPersonConnections(bobProfile, a.id);
  assert(bobConnections.recognizedPeople.some((person) => person.id === alice));
  assert(bobConnections.recognizedPeople.some((person) => person.id === cara), "A→B→C discovery data is available");
  assert.equal(safeNextPath("/events/animecon-london-2026?action=join"), "/events/animecon-london-2026?action=join");
  assert.equal(safeNextPath("https://evil.example/steal"), "/");
  assert.equal(safeNextPath("//evil.example/steal"), "/");
  assert.equal(normalizeSocialProfileUrl("@anime.fan", "instagram"), "https://instagram.com/anime.fan");
  assert.equal(normalizeSocialProfileUrl("https://tiktok.com/@cosplay_creator", "tiktok"), "https://tiktok.com/@cosplay_creator");
  assert.equal(normalizeSocialProfileUrl("https://evil.example/user", "instagram"), "");
  const hero = readFileSync("src/components/GlobalDiscoveryHero.tsx", "utf8");
  assert(hero.includes("export default function GlobalDiscoveryHero"));
  const eventsDb = readFileSync("src/db/events.ts", "utf8");
  assert(eventsDb.includes("GROUP BY recognized_person_id"));
  const recognitionButton = readFileSync("src/components/events/RecognitionButton.tsx", "utf8");
  assert(recognitionButton.includes("RECOGNITION_TIMEOUT_MS"), "recognition UI has a bounded pending state");
  assert(recognitionButton.includes("finally"), "recognition UI always clears its pending state");
  assert(recognitionButton.includes("if (initialRecognized) setRecognized(true)"), "duplicate cards sync after refresh");
  const eventActions = readFileSync("src/lib/actions/events.ts", "utf8");
  assert(eventActions.includes("settleOptionalEventWork"), "analytics and notifications cannot block recognition indefinitely");
  assert(eventActions.includes("eventRecognitionEmail"), "new event recognitions trigger an email alert");
  assert(eventActions.includes("findUserById(target.userId!)"), "recognition email is sent only to the card owner's account email");
  assert(eventActions.includes('if (result === "created" || result === "mutual")'), "duplicate recognition does not enter the notification and email branch");
  assert(eventActions.includes("[event-recognition-save]"), "recognition action returns a recoverable error");
  const recognitionEmail = eventRecognitionEmail({ eventTitle: "AnimeCon <London>", personId: "person id", personName: "A&B", slug: "animecon-london-2026", mutual: false });
  assert.equal(recognitionEmail.subject, "Someone recognised you at AnimeCon <London> ✦");
  assert(recognitionEmail.html.includes("You’ve been recognised ✦"));
  assert(recognitionEmail.html.includes("AnimeCon &lt;London&gt;"), "event email escapes database content");
  assert(recognitionEmail.html.includes("Hi A&amp;B"), "event email escapes the card name");
  assert(recognitionEmail.html.includes("/login?next=%2Fevents%2Fanimecon-london-2026%2Fpeople%2Fperson%2520id%2Frecognized-by"), "event email requires login before opening the recognition page");
  const anonymousRecognitionEmail = eventRecognitionEmail({ eventTitle: "AnimeCon London ’26", personId: "recipient-card", personName: "Recipient", slug: "animecon-london-2026", mutual: false, recognizerId: "recognizer-card" });
  assert(anonymousRecognitionEmail.html.includes("You’ve been recognised ✦"));
  assert(anonymousRecognitionEmail.html.includes("See who recognised you →"));
  assert(anonymousRecognitionEmail.html.includes("/login?next=%2Fevents%2Fanimecon-london-2026%2Fpeople%2Frecognizer-card"), "email requires login before opening the recognizer's card");
  assert(!anonymousRecognitionEmail.html.includes("<img"), "email keeps the recognizer anonymous until click-through");
  assert(anonymousRecognitionEmail.html.includes("Recognition belongs to everyone. Find your people. Recognise and be recognised."), "event brand message stays inside the email body");
  const messageEmail = eventMessageEmail({ eventTitle: "AnimeCon <London>", slug: "animecon-london-2026", conversationId: "chat id", recipientName: "B&b", senderName: "A<lice", senderPhotoUrl: "https://example.test/a.jpg", senderIdentities: ["Artist", "Creator"], commonInterests: ["Frieren"] });
  assert.equal(messageEmail.subject, "A<lice sent you a message at AnimeCon <London> ✦");
  assert(messageEmail.html.includes("A&lt;lice"), "message email escapes the sender name");
  assert(messageEmail.html.includes("https://example.test/a.jpg"), "message email includes the sender avatar");
  assert(messageEmail.html.includes("Artist · Creator"), "message email includes sender identities");
  assert(messageEmail.html.includes("You both like:</strong> Frieren"), "message email highlights common interests");
  assert(messageEmail.html.includes("/login?next=%2Fevents%2Fanimecon-london-2026%2Fmessages%2Fchat%2520id"), "message button requires login and returns to the conversation");
  assert(!messageEmail.html.includes("Hello Bob"), "private message text is not copied into email");
  const messageAction = readFileSync("src/lib/actions/eventMessages.ts", "utf8");
  assert(messageAction.includes("eventMessageEmail"), "each saved event message prepares an email notification");
  assert(messageAction.includes("senderCard?.photoUrl"), "message notification includes the sender avatar");
  assert(messageAction.includes("await sendEmail"), "message notification is sent after the database write");
  assert(messageAction.indexOf("sendEventMessage(") < messageAction.indexOf("await sendEmail"), "email failure cannot prevent the message from being stored");
  const eventCreatedModal = readFileSync("src/components/events/EventCardCreatedModal.tsx", "utf8");
  assert(eventCreatedModal.includes('role="dialog"'), "successful event-card creation opens a confirmation dialog");
  assert(eventCreatedModal.includes("createPortal"), "mobile confirmation escapes transformed page and layout containers");
  assert(eventCreatedModal.includes("document.body"), "mobile confirmation is anchored to the browser viewport");
  assert(eventCreatedModal.includes("experience.shortName"), "confirmation reads the active event name from shared configuration");
  assert(eventCreatedModal.includes("Find your people"), "confirmation gives the user a discovery next step");
  const eventConfig = readFileSync("src/config/socialEvents.ts", "utf8");
  assert(eventConfig.includes('name: "MCM Comic Con London 2026"'), "active event configuration carries the MCM title");
  assert(eventConfig.includes('dateLabel: "23–25 October 2026"'), "active event configuration carries the future MCM dates");
  assert(eventConfig.includes('venue: "ExCeL London"'), "active event configuration carries the MCM venue");
  const eventPage = readFileSync("src/app/events/[slug]/page.tsx", "utf8");
  assert(eventPage.includes("card.id === searchParams.created"), "confirmation only opens for a card owned by the current account");
  assert(eventPage.indexOf("<EventCardCreatedModal") < eventPage.indexOf('className="relative left-1/2'), "mobile modal is outside the transformed full-width page container");
  const eventPersonPage = readFileSync("src/app/events/[slug]/people/[id]/page.tsx", "utf8");
  assert(eventPersonPage.includes("person.userId &&"), "only account-linked event cards expose a RepHear profile");
  assert(eventPersonPage.includes("`/u/${person.userId}`"), "event card links to the owner's main RepHear profile");
  assert(eventPersonPage.includes("’s RepHear profile →"), "main-profile button explains its destination");
  const eventShareTools = readFileSync("src/components/events/EventShareTools.tsx", "utf8");
  assert(eventShareTools.includes("Share my I’M HERE ✦ Card"), "AnimeCon Share Kit presents the card as an I’M HERE identity card");
  assert(eventShareTools.includes("generateOnMount"), "newly created AnimeCon cards preload both share images automatically");
  assert(eventShareTools.includes("Download Square") && eventShareTools.includes("Download Story"), "AnimeCon Share Kit offers downloadable square and story cards");
  assert(eventShareTools.includes("Copy my card link"), "AnimeCon Share Kit offers a copyable tracked destination");
  assert(eventShareTools.includes("WhatsApp") && eventShareTools.includes("Telegram"), "AnimeCon Share Kit exposes explicit channels");
  assert(eventShareTools.includes('"square" | "story"'), "AnimeCon Share Kit provides square and story formats");
  const eventShareRoute = readFileSync("src/app/api/events/[slug]/people/[id]/share-card/route.ts", "utf8");
  assert(eventShareRoute.includes("renderEventShareCard"), "AnimeCon visual cards are server-rendered");
  const eventShareRenderer = readFileSync("src/lib/eventShareCardRenderer.ts", "utf8");
  assert(eventShareRenderer.includes("I’M HERE ✦"), "generated AnimeCon cards carry the I’M HERE identity title");
  assert(eventShareRenderer.includes("Recognised by"), "generated AnimeCon cards show recognition count");
  const siteHeader = readFileSync("src/components/homepage/SiteHeader.tsx", "utf8");
  assert(siteHeader.includes("My Profile"), "signed-in navigation exposes the owner's profile");
  assert(siteHeader.includes("`/u/${userId}`"), "the profile navigation uses the current account id");
  const userProfile = readFileSync("src/app/u/[id]/page.tsx", "utf8");
  assert(userProfile.includes("Everything about you"), "the owner profile introduces the combined personal dashboard");
  assert(userProfile.includes("listUserEventConversations"), "the owner profile includes event messages");
  console.log("event-social-space: all checks passed");
}

run().catch((error) => { console.error(error); process.exit(1); });
